{
 "title": "ICD Kafka JMX",
 "description": "cpu, disk, network, Copyright 2018 Dematic, Corp.",
 "tags": [ "prometheus" ],
 "time": { "from": "2018-06-22T01:11:10.538Z", "to": "2018-06-22T01:53:22.852Z" },
 "templating": {
  "list": [
   {
    "name": "prometheus_job_group",
    "query": "label_values(jvm_memory_bytes_used, job)"
   },
   {
    "name": "server",
    "label": "cluster server ips",
    "query": "label_values(jvm_memory_bytes_used{job=\"$prometheus_job_group\"}, instance)"
   },
   {
    "name": "kafka_topic",
    "query": "label_values(kafka_log_logendoffset{job=\"$prometheus_job_group\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "topic rate per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m]) ) without  (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "total messages across brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ingest rate per second across brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m]) ) without  (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "total bytes IN across cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "bytes in total"
    }
   ]
  },
  {
   "title": "ingest rate  ps  by broker stacked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m]) ",
     "legendFormat": " {{instance}} total"
    }
   ]
  },
  {
   "title": "total messages by broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}",
     "legendFormat": "{{instance}} {{topic}}"
    }
   ]
  },
  {
   "title": "topic ingest per second across brokers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total bytes out across all brokers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "bytes in total"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "est. requests per second STACKED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m])) without (instance)",
     "legendFormat": "total fetch  req- {{topic}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m])) without (instance)",
     "legendFormat": "total producer reqs - {{topic}}"
    }
   ]
  },
  {
   "title": "est. requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m])) without (instance)",
     "legendFormat": "total fetch  req- {{topic}}"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}[1m])) without (instance)",
     "legendFormat": "total producer reqs - {{topic}}"
    }
   ]
  },
  {
   "title": "total fetch/producer requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalfetchrequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "total fetch requests"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_totalproducerequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "total producer requests"
    }
   ]
  },
  {
   "title": "failed requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_failedproducerequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "failed producer req"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_failedfetchrequests_total{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance) ",
     "legendFormat": " failed fetch req"
    }
   ]
  },
  {
   "title": "Memory used with JVM Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$server\",area=\"Heap\"}",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=~\"$server\",area=\"Heap\"}",
     "legendFormat": "xmx  {{instance}}"
    }
   ]
  },
  {
   "title": "Cluster JVM memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$server\",area=\"Heap\"}",
     "legendFormat": "used {{instance}}"
    }
   ]
  },
  {
   "title": "log segments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_numlogsegments{instance=~\"$server\",topic=~\"$kafka_topic\"})  without (partition) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_partition{instance=~\"$server\",topic=~\"$kafka_topic\"}) without (instance) ",
     "legendFormat": "p={{partition}}"
    }
   ]
  }
 ]
}