{
 "title": "Example Spark Driver",
 "description": "cpu, disk, network. Copyright 2018 Dematic, Corp. ",
 "tags": [ "dashboard-ready-to-use" ],
 "time": { "from": "2018-07-09T18:28:02.185Z", "to": "2018-07-09T22:42:52.682Z" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(spark_structured_streaming_batches_total, cluster_id)"
   },
   {
    "name": "driver_app_name",
    "label": "Driver",
    "query": "label_values(spark_structured_streaming_batches_total, driver)"
   },
   {
    "name": "job_id",
    "query": "label_values(spark_structured_streaming_batches_total, job_id)"
   },
   {
    "name": "kafka_job_group",
    "query": "label_values(jvm_memory_bytes_used, job)"
   },
   {
    "name": "kafka_broker",
    "query": "label_values(jvm_memory_bytes_used{job=\"$kafka_job_group\"}, instance)"
   },
   {
    "name": "kafka_topic",
    "query": "label_values(kafka_log_logendoffset{job=\"$kafka_job_group\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Spark input rows  per second",
   "type": "graph",
   "description": "spark_structured_streaming_processed_rows_per_second",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_structured_streaming_input_rows_per_second{cluster_id=~\"$cluster_id\",executor!=\"driver\",driver=~\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "spark input per second"
    },
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=\"$kafka_topic\"}[1m]) ) without  (instance)",
     "legendFormat": "kafka ingest"
    }
   ]
  },
  {
   "title": "Spark rows processed  per second",
   "type": "graph",
   "description": "spark_structured_streaming_processed_rows_per_second",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_structured_streaming_input_rows_per_second{cluster_id=~\"$cluster_id\",executor!=\"driver\",job_id=~\"$job_id\",driver=~\"$driver_app_name\"}",
     "legendFormat": "input ps"
    },
    {
     "expr": "spark_structured_streaming_processed_rows_per_second{cluster_id=~\"$cluster_id\",driver=~\"$driver_app_name\",executor!=\"driver\",job_id=~\"$job_id\"}",
     "legendFormat": "processed ps"
    }
   ]
  },
  {
   "title": "Spark total input rows",
   "type": "graph",
   "description": "spark_structured_streaming_input_rows_total",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_structured_streaming_input_rows_total{cluster_id=~\"$cluster_id\",driver=\"$driver_app_name\",executor!=\"driver\",job_id=~\"$job_id\"}",
     "legendFormat": "{{driver}} "
    }
   ]
  },
  {
   "title": "Kafka Producer vs Spark Consumer",
   "type": "graph",
   "description": "Messages stored in kafka vs Spark consumption",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=\"$kafka_topic\"}) without (instance)",
     "legendFormat": "kafka total"
    },
    {
     "expr": "spark_structured_streaming_input_rows_total{cluster_id=~\"$cluster_id\",executor!=\"driver\",driver=~\"$driver_app_name\", job_id=~\"$job_id\"}",
     "legendFormat": "spark total {{driver}}"
    }
   ]
  },
  {
   "title": "Kafka ingest rate per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\"}[1m]) ) without  (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "query duration in ms",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "spark_structured_streaming_query_duration_ms {cluster_id=~\"$cluster_id\",executor!=\"driver\",driver=\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "{{driver}} job duration  in  ms"
    },
    {
     "expr": "spark_structured_streaming_query_duration_get_batch_ms {cluster_id=~\"$cluster_id\",executor!=\"driver\",driver=\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "get batch"
    },
    {
     "expr": "spark_structured_streaming_query_duration_get_offset_ms {cluster_id=~\"$cluster_id\",executor!=\"driver\",driver=\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "get offset"
    }
   ]
  },
  {
   "title": "Spark rows fetched per job",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "spark_structured_streaming_num_input_rows_for_job {cluster_id=~\"$cluster_id\",executor!=\"driver\",job_id=~\"$job_id\",driver=~\"$driver_app_name\"}",
     "legendFormat": "{{driver}} "
    }
   ]
  },
  {
   "title": "Kafka partition count",
   "type": "graph",
   "description": "Messages stored in kafka vs Spark consumption",
   "gridPos": { "h": 10, "w": 6, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=~\"$kafka_topic\"}) without (instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Driver JVM Heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_heap_used{executor=\"driver\",cluster_id=\"$cluster_id\",driver=\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_total_max{job=~\"spark-push-gateway\",executor=\"driver\",driver=\"$driver_app_name\", cluster_id=\"$cluster_id\",job_id=~\"$job_id\"}",
     "legendFormat": "total max"
    }
   ]
  },
  {
   "title": "Executor JVM Heap used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",executor!=\"driver\",cluster_id=\"$cluster_id\",job_id=~\"$job_id\",driver=\"$driver_app_name\"}",
     "legendFormat": "exc-{{executor}}"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\",executor=\"1\",cluster_id=\"$cluster_id\",driver=~\"$driver_app_name\"}",
     "legendFormat": "memory heap max"
    }
   ]
  },
  {
   "title": "Executor Heap % Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"}/jvm_memory_bytes_max{area=\"heap\",executor!=\"driver\",driver=~\"$driver_app_name\",cluster_id=\"$cluster_id\",job_id=~\"$job_id\"}",
     "legendFormat": "exc-{{executor}}"
    }
   ]
  },
  {
   "title": "alerts kafka ingest rate per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{instance=~\"$kafka_broker\",topic=\"icd_truck_alerts\"}[1m]) ) without  (instance)",
     "legendFormat": "rate per second"
    }
   ]
  },
  {
   "title": "process resident memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"spark-push-gateway\", executor!=\"driver\",cluster_id=\"$cluster_id\",job_id=\"$job_id\"}",
     "legendFormat": "executor {{executor}}"
    }
   ]
  },
  {
   "title": "open file descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds {job=~\"spark-push-gateway\",cluster_id=\"$cluster_id\",job_id=\"$job_id\"}",
     "legendFormat": " executor {{executor}}"
    }
   ]
  },
  {
   "title": "Executor HDFS write ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "executor_filesystem_hdfs_write_ops{cluster_id=\"$cluster_id\",job_id=\"$job_id\"}",
     "legendFormat": "executor={{executor}}"
    }
   ]
  },
  {
   "title": "Executor HDFS read ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "executor_filesystem_hdfs_read_ops{cluster_id=\"$cluster_id\",job_id=\"$job_id\"}",
     "legendFormat": "executor={{executor}}"
    }
   ]
  },
  {
   "title": "gc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum {job=~\"spark-push-gateway\",cluster_id=\"$cluster_id\",cluster_id=\"$cluster_id\",driver=~\"$driver_app_name\", job_id=~\"$job_id\"}",
     "legendFormat": "{{gc}} sum - executor {{executor}}"
    }
   ]
  },
  {
   "title": "Driver jvm threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": " jvm_threads_current {job=~\"spark-push-gateway\",cluster_id=\"$cluster_id\",cluster_id=\"$cluster_id\",driver=~\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "threads - executor {{executor}}"
    },
    {
     "expr": "jvm_threads_peak{job=~\"spark-push-gateway\",cluster_id=\"$cluster_id\",cluster_id=\"$cluster_id\",driver=~\"$driver_app_name\",job_id=~\"$job_id\"}",
     "legendFormat": "peak - executor {{executor}}"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"spark-push-gateway\",cluster_id=\"$cluster_id\",cluster_id=\"$cluster_id\",driver=~\"$driver_app_name\", job_id=~\"$job_id\"}",
     "legendFormat": "daemon threads - executor {{executor}}"
    }
   ]
  }
 ]
}