{
 "title": "Data Pipeline Cluster Machine Metrics",
 "description": "cpu, disk, network for a cluster,Copyright 2018 Dematic, Corp.",
 "tags": [
  "prometheus",
  "dashboard-ready-to-use"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_set_id",
    "query": "regression,dev,devops,devops512,staging,demo"
   },
   {
    "name": "prometheus_job_group",
    "query": "label_values(node_boot_time, job)"
   },
   {
    "name": "server",
    "label": "cluster server ips",
    "query": "label_values(node_boot_time{job=\"$prometheus_job_group\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu usage mode=user % by cores",
   "type": "graph",
   "description": "rate user spent in CPU spent doing each type of work:",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu{instance=~\"$server\",mode=\"user\"}[1m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(node_cpu{instance=~\"$server\",mode=\"user\"}) without (cpu)",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/sda1\",instance=~\"$server\"}-(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$server\"}) )",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail{device=\"/dev/sda1\",instance=~\"$server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "free Memory from OS pov",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " node_memory_MemFree{instance=~\"$server\"}",
     "legendFormat": "{{instance}} "
    },
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "max "
    }
   ]
  },
  {
   "title": "cpu iowait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu{instance=~\"$server\",mode=\"iowait\"}[1m]))",
     "legendFormat": "{{instance}} iowait"
    }
   ]
  },
  {
   "title": "Disk writes IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk reads IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk writes throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate( node_disk_bytes_written {instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk reads throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_read{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "percent disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$server\"} / node_filesystem_size{device=\"/dev/sda1\",instance=~\"$server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Inodes free device=\"/dev/sda1\"",
   "type": "graph",
   "description": "Count of new files and directories you can create",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{device=\"/dev/sda1\",instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{instance=~\"$server\",device!~\"lo\"}[1m])",
     "legendFormat": "receive {{instance}}"
    },
    {
     "expr": "irate(node_network_transmit_packets{instance=~\"$server\",device!~\"lo\"}[1m])",
     "legendFormat": "transmit {{instance}}"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs{instance=~\"$server\",device!~\"lo\"}[1m])",
     "legendFormat": "{{instance}} receive "
    },
    {
     "expr": "irate(node_network_transmit_errs{instance=~\"$server\",device!~\"lo\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server\"}",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Total Max Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{device=\"/dev/sda1\",instance=~\"$server\"} ",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk Max Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{device=\"/dev/sda1\",instance=~\"$server\"} ",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "MAX IOPS (read or write each)",
   "type": "graph",
   "description": "both numbers same since max allowed is 30xGB",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "30*node_filesystem_size{device=\"/dev/sda1\",instance=~\"$server\"}/ 1000000000 ",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "STACKED System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "STACKED Disk writes IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "STACKED Network sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$server\",device!~\"lo\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "STACKED Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}