{
 "title": "ICD Cluster Disk Only",
 "description": "Disk metrics for pipeline including Kafka/yarn/influxdb. Copyright 2018 Dematic, Corp.  ",
 "tags": [
  "prometheus",
  "dashboard-ready-to-use"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_set_id", "query": "devops,demo" },
   {
    "name": "kafka_server",
    "label": "kafka  ips",
    "query": "label_values(node_boot_time{job=\"$cluster_set_id-kafka\"}, instance)"
   },
   {
    "name": "yarn_server",
    "label": "yarn ips",
    "query": "label_values(node_boot_time{job=\"$cluster_set_id-yarn\"}, instance)"
   },
   {
    "name": "simulator",
    "label": "kafka producer servers",
    "query": "label_values(node_boot_time{job=\"$cluster_set_id-kafka-producers\"}, instance)"
   },
   {
    "name": "influxdb_server",
    "query": "label_values(node_boot_time{job=\"influxdb-$cluster_set_id\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kafka % disk free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$kafka_server\"} / node_filesystem_size{device=\"/dev/sda1\",instance=~\"$kafka_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "kafka Disk avail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail{device=\"/dev/sda1\",instance=~\"$kafka_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Kafka disk IOPS  write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$kafka_server\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka disk IOPS  reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$kafka_server\"}[1m]))"
    }
   ]
  },
  { "title": "YARN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "YARN % disk free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$yarn_server\"} / node_filesystem_size{device=\"/dev/sda1\",instance=~\"$yarn_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "YARN  Disk avail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail{device=\"/dev/sda1\",instance=~\"$yarn_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "yarn disk IOPS  write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "yarn disk IOPS  reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$yarn_server\"}[1m]))"
    }
   ]
  },
  {
   "title": "yarn disk bytes read ps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "yarn IO time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_ms{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "yarn disk IOPS  stacked",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    },
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "yarn disk IOPS  sum",
   "type": "graph",
   "description": "read and write",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$yarn_server\"}[1m])) +sum by (instance) (irate(node_disk_reads_completed{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  { "title": "Influx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "influx percent disk free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$influxdb_server\"} / node_filesystem_size{device=\"/dev/sda1\",instance=~\"$influxdb_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "influx Disk avail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail{device=\"/dev/sda1\",instance=~\"$influxdb_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "influx disk IOPS  write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$influxdb_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "influx OPS  reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$influxdb_server\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "yarn disk bytes written ps",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (irate(node_disk_bytes_written{instance=~\"$yarn_server\"}[1m]))",
       "legendFormat": "{{instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "STACKED yarn disk bytes written ps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_bytes_written{instance=~\"$yarn_server\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "simulator Disk avail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail{device=\"/dev/sda1\",instance=~\"$simulator\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "simulator disk IOPS  write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_writes_completed{instance=~\"$simulator\"}[1m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "simulator IOPS  reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed{instance=~\"$simulator\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "simulator percent disk free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{device=\"/dev/sda1\",instance=~\"$simulator\"} / node_filesystem_size{device=\"/dev/sda1\",instance=~\"$simulator\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "kafka TOTAL Disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{device=\"/dev/sda1\",instance=~\"$kafka_server\"} ",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Kafka Max IOPS Write or Read each",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "30*node_filesystem_size{device=\"/dev/sda1\",instance=~\"$kafka_server\"}/ 1000000000",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Max IOPS Throughput MB/s",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": ".48*node_filesystem_size{device=\"/dev/sda1\",instance=~\"$kafka_server\"}/1000000000",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "YARN GCP published MAX throughput MB per sec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": ".48*node_filesystem_size{device=\"/dev/sda1\",instance=~\"$yarn_server\"}/1000000000",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "YARN MAX IOPS Write",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "30*node_filesystem_size{device=\"/dev/sda1\",instance=~\"$yarn_server\"}/ 1000000000 ",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "YARN Disk Size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size{device=\"/dev/sda1\",instance=~\"$yarn_server\"})",
     "legendFormat": "{{instance}} "
    }
   ]
  }
 ]
}